#===============================================================================================
# Suite: upi-dmfg-deployment.yaml
# Conf: conf/reef/cephadm/upi/
# UPI test cases for
#    - Bootstrap
#    - Host management
#    - Service deployment
#    - Client Configuration
#    - IOs (RGW, RBD, CEPHFS and NFS)
#    - Ceph-Volume scenarios
#===============================================================================================
tests:
  - test:
      abort-on-fail: true
      desc: Install software pre-requisites for cluster deployment.
      module: install_prereq.py
      name: setup pre-requisites

  - test:
      name: Deploy cluster using cephadm
      desc: bootstrap and deploy services
      module: test_cephadm.py
      polarion-id: CEPH-83573713
      config:
        steps:
          - config:
              command: bootstrap
              service: cephadm
              args:
                mon-ip: node1
                orphan-initial-daemons: true
                registry-url: registry.redhat.io
                allow-fqdn-hostname: true
              base_cmd_args:
                verbose: true
          - config:
              command: add_hosts
              service: host
              args:
                attach_ip_address: true
                labels: apply-all-labels
          - config:
              command: apply
              service: osd
              args:
                all-available-devices: true
          - config:
              command: apply
              service: mgr
              args:
                placement:
                  label: mgr
          - config:
              command: apply
              service: mon
              args:
                placement:
                  label: mon
          - config:
              command: shell
              args:
                - ceph
                - fs
                - volume
                - create
                - cephfs
          - config:
              args:
                placement:
                  label: mds
              base_cmd_args:
                verbose: true
              command: apply
              pos_args:
                - cephfs
              service: mds
          - config:
              command: apply
              service: rgw
              pos_args:
                - rgw.1
              args:
                placement:
                  label: rgw
          - config:
              args:
                - "ceph osd pool create rbd"
              command: shell
          - config:
              args:
                - "rbd pool init rbd"
              command: shell
      destroy-cluster: false
      abort-on-fail: true

  - test:
      abort-on-fail: true
      config:
        command: add
        copy_admin_keyring: true
        id: client.1
        install_packages:
          - ceph-common
        node: node10
      desc: "Configure the Cephfs client system 1"
      destroy-cluster: false
      module: test_client.py
      name: "configure client"

  - test:
      abort-on-fail: true
      config:
        command: add
        copy_admin_keyring: true
        id: client.2
        install_packages:
          - ceph-common
        node: node11
      desc: "Configure the Cephfs client system 2"
      destroy-cluster: false
      module: test_client.py
      name: "configure client"

  - test:
      name: Executes RGW, RBD and FS operations
      desc: Run object, block and filesystem IO operations parallelly.
      module: test_parallel.py
      parallel:
        - test:
            name: CephFS IO
            desc: CephFS IO with specfic percentage
            module: test_io.py
            config:
              wait_for_io: True
              cephfs:
                "fill_data": 30
                "num_of_clients": 1
                "io_tool": "smallfile"
                "mount": "fuse"
                "batch_size": 30
                "filesystem": "cephfs_io_1"
                "mount_dir": ""
            abort-on-fail: false
        - test:
            config:
              script-name: test_Mbuckets_with_Nobjects.py
              config-file-name: test_Mbuckets_with_Nobjects.yaml
              timeout: 300
            desc: test to create "M" no of buckets and "N" no of objects
            module: sanity_rgw.py
            name: Test M buckets with N objects
            polarion-id: CEPH-9789
        - test:
            config:
              ec-pool-k-m: 2,1
              ec-pool-only: False
              ec_pool_config:
                pool: rbd_pool
                data_pool: rbd_ec_pool
                ec_profile: rbd_ec_profile
                image: rbd_image
                image_thick_provision: rbd_thick_image
                snap_thick_provision: rbd_thick_snap
                clone_thick_provision: rbd_thick_clone
                thick_size: 2G
                size: 10G
                snap: rbd_ec_pool_snap
                clone: rbd_ec_pool_clone
              rep_pool_config:
                pool: rbd_rep_pool
                image: rbd_rep_image
                image_thick_provision: rbd_rep_thick_image
                snap_thick_provision: rbd_rep_thick_snap
                clone_thick_provision: rbd_rep_thick_clone
                thick_size: 2G
                size: 10G
                snap: rbd_rep_pool_snap
                clone: rbd_rep_pool_clone
              operations:
                map: true
                io: true
                nounmap: false
            desc: Run RBD tier-0 operations
            polarion-id: CEPH-83575401
            destroy-cluster: false
            module: rbd_tier0.py
            name: Run RBD tier-0 operations

  - test:
      name: Check cluster health
      desc: Check Ceph cluster health after IOs
      module: exec.py
      config:
        cmd: ceph -s
        sudo: True

  - test:
      name: Stopping mon and mgr service
      desc: Test Ceph orch stop mon and mgr services
      module: test_cluster_service_operations.py
      polarion-id: CEPH-83574435
      config:
        operation: stop
        service:
          - "mon"
          - "mgr"
      destroy-cluster: false
      abort-on-fail: true

  - test:
      name: OSD service ops using systemctl
      desc: Test stop and start OSD service using systemctl
      module: test_osd_service_operations.py
      polarion-id: CEPH-83573802
      destroy-cluster: false
      abort-on-fail: true
