# Suite is to be used to verify osd deployment workflows
# to be run in regression conf: 4-node-ec-cluster-1-client.yaml

tests:
  - test:
      name: setup install pre-requisistes
      desc: Setup phase to deploy the required pre-requisites for running the tests.
      module: install_prereq.py
      abort-on-fail: true

  - test:
      name: cluster deployment
      desc: Execute the cluster deployment workflow.
      module: test_cephadm.py
      abort-on-fail: true
      config:
        verify_cluster_health: true
        steps:
          - config:
              command: bootstrap
              service: cephadm
              base_cmd_args:
                verbose: true
              args:
                mon-ip: node1

  - test:
      name: Add host
      desc: Add new host node with IP address
      module: test_host.py
      config:
        command: add_hosts
        service: host
        args:
          nodes:
            - node1
            - node2
            - node3
            - node4
            - node5
          attach_ip_address: true
          labels: apply-all-labels
      destroy-cluster: false
      abort-on-fail: true

  - test:
      name: Mgr and Mon deployment
      desc: Add Mgr and Mon daemons
      module: test_cephadm.py
      polarion-id: CEPH-83573746
      abort-on-fail: true
      config:
        steps:
          - config:
              command: apply
              service: mgr
              args:
                placement:
                  label: mgr
          - config:
              command: apply
              service: mon
              args:
                placement:
                  label: mon

  - test:
      name: OSD deployment
      desc: Add OSD services using spec file.
      module: test_cephadm.py
      polarion-id: CEPH-83573746
      abort-on-fail: true
      config:
        steps:
          - config:
              command: apply_spec
              service: orch
              validate-spec-services: true
              specs:
                - service_type: osd
                  service_id: osds
                  encrypted: "true" # boolean as string
                  placement:
                    label: osd
                  spec:
                    data_devices:
                      all: "true"

  - test:
      name: MDS Service deployment with spec
      desc: Add MDS services using spec file
      module: test_cephadm.py
      polarion-id: CEPH-83574728
      config:
        steps:
          - config:
              command: shell
              args: # arguments to ceph orch
                - ceph
                - fs
                - volume
                - create
                - cephfs
          - config:
              command: apply_spec
              service: orch
              validate-spec-services: true
              specs:
                - service_type: mds
                  service_id: cephfs
                  placement:
                    label: mds
          # Adding below WA to set bulk flag to false until bug fix : 2308623
          - config:
              command: shell
              args: # arguments to ceph orch
                - "ceph osd pool set cephfs.cephfs.data bulk false"

  - test:
      name: RGW Service deployment
      desc: RGW Service deployment
      module: test_cephadm.py
      polarion-id: CEPH-83574728
      config:
        steps:
          - config:
              command: apply
              service: rgw
              pos_args:
                - rgw.1
              args:
                placement:
                  label: rgw

  - test:
      name: Configure client admin
      desc: Configures client admin node on cluster
      module: test_client.py
      abort-on-fail: true
      polarion-id: CEPH-83573758
      config:
        command: add
        id: client.1 # client Id (<type>.<Id>)
        node: node6 # client node
        install_packages:
          - ceph-common
        copy_admin_keyring: true # Copy admin keyring to node
        caps: # authorize client capabilities
          mon: "allow *"
          osd: "allow *"
          mds: "allow *"
          mgr: "allow *"

  - test:
      name: Enable logging to file
      module: rados_prep.py
      config:
        log_to_file: true
      desc: Change config options to enable logging to file

  - test:
      name: 1 - OSD deployment tests - raw data device - spec file
      module: osd_deploy_tests.py
      polarion-id: CEPH-83632255
      config:
        test_scenarios:
          - scenario1
      desc: OSD deployment tests - raw data device - spec file

  - test:
      name: 2 - OSD deployment tests - lvm data device - spec file
      module: osd_deploy_tests.py
      polarion-id: CEPH-83632255
      config:
        test_scenarios:
          - scenario2
      desc: OSD deployment tests - lvm data device - spec file

  - test:
      name: 3 - OSD deployment tests - lvm data and db device - spec file
      module: osd_deploy_tests.py
      polarion-id: CEPH-83632255
      config:
        test_scenarios:
          - scenario3
      desc: OSD deployment tests -  lvm data and db device - spec file

  - test:
      name: 4 - OSD deployment tests - lvm data, db and wal device - spec file
      module: osd_deploy_tests.py
      polarion-id: CEPH-83632255
      config:
        test_scenarios:
          - scenario4
      desc: OSD deployment tests - lvm data, db and wal device - spec file

  - test:
      name: 5 - OSD deployment tests - raw data and db device - spec file
      module: osd_deploy_tests.py
      polarion-id: CEPH-83632255
      config:
        test_scenarios:
          - scenario5
      desc: OSD deployment tests - raw data and db device - spec file

  - test:
      name: 6 - OSD deployment tests - raw data, db and wal device - spec file
      module: osd_deploy_tests.py
      polarion-id: CEPH-83632255
      config:
        test_scenarios:
          - scenario6
      desc: OSD deployment tests - raw data, db and wal device - spec file
