# Test suite for for baremetal rgw-multisite deployment and testing multisite sync at scale.
#
# This suite deploys a Longevity environment on baremetal machines. It is a multisite environment with each site having a storage capacity of 617Tb.
# each site has around 4 osd hosts and a total of 16 osds.
# A single realm (India) spanning across two RHCS clusters. It has a
# zonegroup (shared) which also spans across the clusters. There exists a master (primary)
# and secondary (secondary) zone within this group. The master zone is part of the pri
# cluster whereas the sec zone is part of the sec datacenter (cluster).

# The deployment is evaluated by running IOs across the environments.
# tested with conf file: conf/baremetal/extensa_mero_multisite_1admin_5node_along_client.yaml

tests:
  - test:
      abort-on-fail: true
      desc: Install software pre-requisites for cluster deployment
      module: install_prereq.py
      name: setup pre-requisites

  - test:
      abort-on-fail: true
      clusters:
        ceph-pri:
          config:
            verify_cluster_health: true
            steps:
              - config:
                  command: bootstrap
                  service: cephadm
                  args:
                    registry-url: registry.redhat.io
                    mon-ip: mero001
                    allow-fqdn-hostname: true
                    orphan-initial-daemons: true
                    initial-dashboard-password: admin@123
                    dashboard-password-noupdate: true
              - config:
                  command: add_hosts
                  service: host
                  args:
                    attach_ip_address: true
                    labels: apply-all-labels
              - config:
                  command: apply
                  service: mgr
                  args:
                    placement:
                      label: mgr
              - config:
                  command: apply
                  service: mon
                  args:
                    placement:
                      label: mon
              - config:
                  command: apply
                  service: osd
                  args:
                    all-available-devices: true
              - config:
                  command: apply
                  service: rgw
                  pos_args:
                    - shared.pri.io
                  args:
                    port: 8080
                    placement:
                      nodes:
                        - mero003
                        - mero004
              - config:
                  command: apply
                  service: rgw
                  pos_args:
                    - shared.pri.sync
                  args:
                    port: 8080
                    placement:
                      nodes:
                        - mero001
                        - mero002
        ceph-sec:
          config:
            verify_cluster_health: true
            steps:
              - config:
                  command: bootstrap
                  service: cephadm
                  args:
                    registry-url: registry.redhat.io
                    mon-ip: mero005
                    allow-fqdn-hostname: true
                    orphan-initial-daemons: true
                    initial-dashboard-password: admin@123
                    dashboard-password-noupdate: true
              - config:
                  command: add_hosts
                  service: host
                  args:
                    attach_ip_address: true
                    labels: apply-all-labels
              - config:
                  command: apply
                  service: mgr
                  args:
                    placement:
                      label: mgr
              - config:
                  command: apply
                  service: mon
                  args:
                    placement:
                      label: mon
              - config:
                  command: apply
                  service: osd
                  args:
                    all-available-devices: true
              - config:
                  command: apply
                  service: rgw
                  pos_args:
                    - shared.sec.io
                  args:
                    port: 8080
                    placement:
                      nodes:
                        - mero009
                        - mero011
              - config:
                  command: apply
                  service: rgw
                  pos_args:
                    - shared.sec.sync
                  args:
                    port: 8080
                    placement:
                      nodes:
                        - mero005
                        - mero007
      desc: Bootstrap clusters using cephadm.
      polarion-id: CEPH-83573386
      destroy-cluster: false
      module: test_cephadm.py
      name: Bootstrap clusters

  - test:
      clusters:
        ceph-pri:
          config:
            verify_cluster_health: true
            steps:
              - config:
                  command: apply_spec
                  service: orch
                  validate-spec-services: true
                  specs:
                    - service_type: prometheus
                      placement:
                        count: 1
                        nodes:
                          - mero001
                    - service_type: grafana
                      placement:
                        nodes:
                          - mero001
                    - service_type: alertmanager
                      placement:
                        count: 1
                    - service_type: node-exporter
                      placement:
                        host_pattern: "*"
                    - service_type: crash
                      placement:
                        host_pattern: "*"
        ceph-sec:
          config:
            verify_cluster_health: true
            steps:
              - config:
                  command: apply_spec
                  service: orch
                  validate-spec-services: true
                  specs:
                    - service_type: prometheus
                      placement:
                        count: 1
                        nodes:
                          - mero005
                    - service_type: grafana
                      placement:
                        nodes:
                          - mero005
                    - service_type: alertmanager
                      placement:
                        count: 1
                    - service_type: node-exporter
                      placement:
                        host_pattern: "*"
                    - service_type: crash
                      placement:
                        host_pattern: "*"
      name: Monitoring Services deployment
      desc: Add monitoring services using spec file.
      module: test_cephadm.py
      polarion-id: CEPH-83574727

  - test:
      abort-on-fail: true
      clusters:
        ceph-pri:
          config:
            command: add
            id: client.pri
            node:
              - mero001
              - mero004
            install_packages:
              - ceph-common
            copy_admin_keyring: true
        ceph-sec:
          config:
            command: add
            id: client.sec
            node:
              - mero005
              - mero011
            install_packages:
              - ceph-common
            copy_admin_keyring: true
      desc: Configure the RGW client system
      polarion-id: CEPH-83573758
      destroy-cluster: false
      module: test_client.py
      name: configure client

  - test:
      abort-on-fail: true
      clusters:
        ceph-pri:
          config:
            cephadm: true
            commands:
              - "radosgw-admin realm create --rgw-realm india --default"
              - "radosgw-admin zonegroup create --rgw-realm india --rgw-zonegroup shared --endpoints http://{node_ip:mero001}:8080,http://{node_ip:mero002}:8080 --master --default"
              - "radosgw-admin zone create --rgw-realm india --rgw-zonegroup shared --rgw-zone primary --endpoints http://{node_ip:mero001}:8080,http://{node_ip:mero002}:8080 --master --default"
              - "radosgw-admin period update --rgw-realm india --commit"
              - "radosgw-admin user create --uid=repuser --display_name='Replication user' --access-key test123 --secret test123 --rgw-realm india --system"
              - "radosgw-admin zone modify --rgw-realm india --rgw-zonegroup shared --rgw-zone primary --access-key test123 --secret test123"
              - "radosgw-admin period update --rgw-realm india --commit"
              - "ceph config set client.rgw.shared.pri.sync rgw_realm india"
              - "ceph config set client.rgw.shared.pri.sync rgw_zonegroup shared"
              - "ceph config set client.rgw.shared.pri.sync rgw_zone primary"
              - "ceph config set client.rgw.shared.pri.io rgw_realm india"
              - "ceph config set client.rgw.shared.pri.io rgw_zonegroup shared"
              - "ceph config set client.rgw.shared.pri.io rgw_zone primary"
              - "ceph config set client.rgw.shared.pri.io rgw_run_sync_thread false"
              - "ceph config set global cluster_network 172.20.20.0/24"
              - "ceph orch redeploy osd"
              - "ceph orch restart {service_name:shared.pri.io}"
              - "ceph orch restart {service_name:shared.pri.sync}"
        ceph-sec:
          config:
            cephadm: true
            commands:
              - "sleep 120"
              - "radosgw-admin realm pull --rgw-realm india --url http://{node_ip:mero001}:8080 --access-key test123 --secret test123 --default"
              - "radosgw-admin period pull --url http://{node_ip:mero001}:8080 --access-key test123 --secret test123"
              - "radosgw-admin zone create --rgw-realm india --rgw-zonegroup shared --rgw-zone secondary --endpoints http://{node_ip:mero005}:8080,http://{node_ip:mero007}:8080 --access-key test123 --secret test123"
              - "radosgw-admin period update --rgw-realm india --commit"
              - "ceph config set client.rgw.shared.sec.sync rgw_realm india"
              - "ceph config set client.rgw.shared.sec.sync rgw_zonegroup shared"
              - "ceph config set client.rgw.shared.sec.sync rgw_zone secondary"
              - "ceph config set client.rgw.shared.sec.io rgw_realm india"
              - "ceph config set client.rgw.shared.sec.io rgw_zonegroup shared"
              - "ceph config set client.rgw.shared.sec.io rgw_zone secondary"
              - "ceph config set client.rgw.shared.sec.io rgw_run_sync_thread false"
              - "ceph config set global cluster_network 172.20.20.0/24"
              - "ceph orch redeploy osd"
              - "ceph orch restart {service_name:shared.sec.io}"
              - "ceph orch restart {service_name:shared.sec.sync}"
      desc: Setting up RGW multisite replication environment
      module: exec.py
      name: setup multisite
      polarion-id: CEPH-10362

  - test:
      abort-on-fail: true
      clusters:
        ceph-pri:
          config:
            haproxy_clients:
              - mero001
            rgw_endpoints:
              - "mero001:8080"
              - "mero002:8080"
        ceph-sec:
          config:
            haproxy_clients:
              - mero005
            rgw_endpoints:
              - "mero005:8080"
              - "mero007:8080"
      desc: Configure HAproxy for sync rgw
      module: haproxy.py
      name: Configure HAproxy for sync rgw
      polarion-id: CEPH-83572703

  - test:
      abort-on-fail: true
      clusters:
        ceph-pri:
          config:
            cephadm: true
            commands:
              - "radosgw-admin zonegroup modify --endpoints=http://{node_ip:mero001}:5000 --rgw-zonegroup shared --rgw-realm india --access-key test123 --secret-key test123"
              - "radosgw-admin zone modify --endpoints=http://{node_ip:mero001}:5000 --rgw-zonegroup shared --rgw-realm india --rgw-zone primary --access-key test123 --secret-key test123"
              - "radosgw-admin period update --commit"
        ceph-sec:
          config:
            cephadm: true
            commands:
              - "sleep 120"
              - "radosgw-admin zone modify --rgw-zone secondary --endpoints=http://{node_ip:mero005}:5000 --access-key test123 --secret-key test123"
              - "radosgw-admin period update --commit"
      desc: Setting up RGW multisite replication environment
      module: exec.py
      name: setup multisite
      polarion-id: CEPH-10362

  - test:
      clusters:
        ceph-pri:
          config:
            cephadm: true
            commands:
              - "ceph versions"
              - "radosgw-admin sync status"
              - "ceph -s"
              - "radosgw-admin realm list"
              - "radosgw-admin zonegroup list"
              - "radosgw-admin zone list"
              - "radosgw-admin user list"
        ceph-sec:
          config:
            cephadm: true
            commands:
              - "ceph versions"
              - "radosgw-admin sync status"
              - "ceph -s"
              - "radosgw-admin realm list"
              - "radosgw-admin zonegroup list"
              - "radosgw-admin zone list"
              - "radosgw-admin user list"
      desc: Retrieve the configured environment details
      polarion-id: CEPH-83575227
      module: exec.py
      name: get shared realm info

  - test:
      abort-on-fail: true
      clusters:
        ceph-pri:
          config:
            haproxy_clients:
              - mero003
              - mero004
            rgw_endpoints:
              - "mero003:8080"
              - "mero004:8080"
        ceph-sec:
          config:
            haproxy_clients:
              - mero009
              - mero011
            rgw_endpoints:
              - "mero009:8080"
              - "mero011:8080"
      desc: Configure HAproxy for io rgw
      module: haproxy.py
      name: Configure HAproxy for io rgw
      polarion-id: CEPH-83572703

  - test:
      abort-on-fail: true
      clusters:
        ceph-pri:
          config:
            controllers:
              - mero003
            drivers:
              count: 3
              hosts:
                - mero003
                - mero004
        ceph-sec:
          config:
            controllers:
              - mero009
            drivers:
              count: 2
              hosts:
                - mero009
                - mero011
      desc: Start COS Bench controller and driver
      module: cosbench.py
      name: deploy cosbench
