---
tests:
  -
    test:
      abort-on-fail: true
      desc: "Setup phase to deploy the required pre-requisites for running the tests."
      module: install_prereq.py
      name: "setup install pre-requisistes"
  -
    test:
      abort-on-fail: true
      config:
        steps:
          -
            config:
              args:
                mon-ip: node1
                orphan-initial-daemons: true
                registry-url: registry.redhat.io
                allow-fqdn-hostname: true
                skip-monitoring-stack: true
              base_cmd_args:
                verbose: true
              command: bootstrap
              service: cephadm
          -
            config:
              args:
                attach_ip_address: true
                labels: apply-all-labels
              command: add_hosts
              service: host
          -
            config:
              args:
                placement:
                  label: mgr
              command: apply
              service: mgr
          -
            config:
              args:
                placement:
                  label: mon
              command: apply
              service: mon
          -
            config:
              args:
                - ceph
                - fs
                - volume
                - create
                - cephfs
              command: shell
          -
            config:
              args:
                placement:
                  label: mds
              base_cmd_args:
                verbose: true
              command: apply
              pos_args:
                - cephfs
              service: mds
          - config:
              args:
                - ceph
                - fs
                - set
                - cephfs
                - max_mds
                - "2"
              command: shell
          - config:
              args:
                - "ceph config set global osd_pool_default_pg_autoscale_mode on"
              command: shell
      desc: "Execute the cluster deployment workflow with label placement."
      destroy-cluster: false
      module: test_cephadm.py
      name: "cluster deployment"
      polarion-id: CEPH-83573777
  - test:
      name: Configure OSD
      module: homogenous_osd_cluster.py
      desc: Deploy OSDs on specifc devices on the node.
      abort-on-fail: true
  -
    test:
      abort-on-fail: true
      config:
        command: add
        copy_admin_keyring: true
        id: client.1
        install_packages:
          - ceph-common
        node: node5
      desc: "Configure the Cephfs client system 1"
      destroy-cluster: false
      module: test_client.py
      name: "configure client"
  - test:
      abort-on-fail: true
      config:
        command: add
        copy_admin_keyring: true
        id: client.2
        install_packages:
          - ceph-common
        node: node6
      desc: "Configure the Cephfs client system 2"
      destroy-cluster: false
      module: test_client.py
      name: "configure client"
  - test:
      abort-on-fail: true
      config:
        command: add
        copy_admin_keyring: true
        id: client.3
        install_packages:
          - ceph-common
        node: node7
      desc: "Configure the Cephfs client system 3"
      destroy-cluster: false
      module: test_client.py
      name: "configure client"
  - test:
      abort-on-fail: true
      config:
        command: add
        copy_admin_keyring: true
        id: client.4
        install_packages:
          - ceph-common
        node: node8
      desc: "Configure the Cephfs client system 4"
      destroy-cluster: false
      module: test_client.py
      name: "configure client"
  - test:
      abort-on-fail: false
      desc: "Fill the cluster with specific percentage"
      name: "Fill Cluster"
      module: test_io.py
      config:
        wait_for_io: True
        cephfs:
          "fill_data": 10
          "num_of_clients": 4
          "io_tool": "smallfile"
          "mount": "fuse"
          "batch_size": 30
          "filesystem": "cephfs_io_1"
          "mount_dir": ""
  - test:
      name: EC pool LC
      module: rados_prep.py
      polarion-id: CEPH-83571632
      config:
        ec_pool:
          create: true
          profile_name: ec86_profile
          pool_name: ec86_pool
          pg_num: 64
          k: 8
          m: 6
          create_rule: false
          app_name: msr #set to avoid rados cleanup
          crush-osds-per-failure-domain: 4
          crush-num-failure-domains: 4
          plugin: jerasure
          crush-failure-domain: host
      desc: Create 8+6 MSR EC pools
