---
# test configuration info to set ceph configuration features
configs:
  - method: set
    class: Config
    component: ceph
    args:
      who: global
      option: rbd_default_features
      value: 125
    role: client
